profession = [
  { code: 0, name: 'Administrador de Rede' },
  { code: 1, name: 'Administrador(a)' },
  { code: 2, name: 'Administrador(a) de Banco de Dados' },
  { code: 3, name: 'Administrador(a) de Empresas' },
  { code: 4, name: 'Administrador(a) de Recursos Humanos' },
  { code: 5, name: 'Administrador(a) Hospitalar' },
  { code: 6, name: 'Administradora de Serviços do Lar' },
  { code: 7, name: 'Advogado(a)' },
  { code: 8, name: 'Agente Ambiental' },
  { code: 9, name: 'Agricultor(a)' },
  { code: 10, name: 'Agrônomo(a)' },
  { code: 11, name: 'Agropecuarista' },
  { code: 12, name: 'Ajudante de Caminhão' },
  { code: 13, name: 'Ajudante de Composição' },
  { code: 14, name: 'Ajudante de Foguista' },
  { code: 15, name: 'Ajudante de Vidreiro' },
  { code: 16, name: 'Almoxarife' },
  { code: 17, name: 'Analista' },
  { code: 18, name: 'Analista Administrativo (a)' },
  { code: 19, name: 'Analista Contábil' },
  { code: 20, name: 'Analista de Administração de Pessoal' },
  { code: 21, name: 'Analista de Captação' },
  { code: 22, name: 'Analista de Contratos' },
  { code: 23, name: 'Analista de Controladoria' },
  { code: 24, name: 'Analista de Controle Interno' },
  { code: 25, name: 'Analista de Crédito' },
  { code: 26, name: 'Analista de Custos' },
  { code: 27, name: 'Analista de Departamento Pessoal' },
  { code: 28, name: 'Analista de Exportação' },
  { code: 29, name: 'Analista de Faturamento' },
  { code: 30, name: 'Analista de IT' },
  { code: 31, name: 'Analista de Laboratório' },
  { code: 32, name: 'Analista de Logística' },
  { code: 33, name: 'Analista de Marketing' },
  { code: 34, name: 'Analista de Negócios' },
  { code: 35, name: 'Analista de Orçamentos' },
  { code: 36, name: 'Analista de Organização e Métodos' },
  { code: 37, name: 'Analista de Pessoal' },
  { code: 38, name: 'Analista de Recursos Humanos' },
  { code: 39, name: 'Analista de Remuneração Senior' },
  { code: 40, name: 'Analista de Sistemas' },
  { code: 41, name: 'Analista de Suporte Administrativo' },
  { code: 42, name: 'Analista de Suporte Pleno' },
  { code: 43, name: 'Analista de Tecidos' },
  { code: 44, name: 'Analista de Vendas' },
  { code: 45, name: 'Analista Financeiro' },
  { code: 46, name: 'Analista Fiscal' },
  { code: 47, name: 'Analista Senior de Previdência Privada' },
  { code: 48, name: 'Analista Tributária' },
  { code: 49, name: 'Apicultor(a)' },
  { code: 50, name: 'Aposentado(a)' },
  { code: 51, name: 'Armador de Pesca' },
  { code: 52, name: 'Arquiteto(a)' },
  { code: 53, name: 'Artesão(ã)' },
  { code: 54, name: 'Assistente Administrativo' },
  { code: 55, name: 'Assistente Comercial' },
  { code: 56, name: 'Assistente Contábil' },
  { code: 57, name: 'Assistente de Contas' },
  { code: 58, name: 'Assistente de Departamento Pessoal' },
  { code: 59, name: 'Assistente de Escritório' },
  { code: 60, name: 'Assistente de Faturamento' },
  { code: 61, name: 'Assistente de Gerencia de R.H.' },
  { code: 62, name: 'Assistente de Hotelaria Hospitalar' },
  { code: 63, name: 'Assistente de Planejamento' },
  { code: 64, name: 'Assistente de Processo' },
  { code: 65, name: 'Assistente de Produção' },
  { code: 66, name: 'Assistente de Recursos Humanos' },
  { code: 67, name: 'Assistente de Suprimentos' },
  { code: 68, name: 'Assistente Financeiro' },
  { code: 69, name: 'Assistente Jurídico' },
  { code: 70, name: 'Assistente Social' },
  { code: 71, name: 'Assistente Técnico Operacional' },
  { code: 72, name: 'Atendente' },
  { code: 73, name: 'Ator' },
  { code: 74, name: 'Atriz' },
  { code: 75, name: 'Auditor(a)' },
  { code: 76, name: 'Auditor(a) Fiscal' },
  { code: 77, name: 'Autônomo(a)' },
  { code: 78, name: 'Aux. de Serviços Gerais' },
  { code: 79, name: 'Auxiliar Acadêmico' },
  { code: 80, name: 'Auxiliar Administrativo' },
  { code: 81, name: 'Auxiliar Contábil' },
  { code: 82, name: 'Auxiliar de Compras' },
  { code: 83, name: 'Auxiliar de Cozinha' },
  { code: 84, name: 'Auxiliar de Departamento de Crédito' },
  { code: 85, name: 'Auxiliar de Departamento Financeiro' },
  { code: 86, name: 'Auxiliar de Departamento Fiscal' },
  { code: 87, name: 'Auxiliar de eletricista' },
  { code: 88, name: 'Auxiliar de Enfermagem' },
  { code: 89, name: 'Auxiliar de Escritório' },
  { code: 90, name: 'Auxiliar de Inspeção de Qualidade' },
  { code: 91, name: 'Auxiliar de Laboratório' },
  { code: 92, name: 'Auxiliar de Produção' },
  { code: 93, name: 'Auxiliar de Registro de Saúde' },
  { code: 94, name: 'Auxiliar de RH' },
  { code: 95, name: 'Auxiliar de Serviços' },
  { code: 96, name: 'Auxiliar Financeiro' },
  { code: 97, name: 'Auxiliar Operacional' },
  { code: 98, name: 'Auxiliar Técnico' },
  { code: 99, name: 'Avicultor( a )' },
  { code: 100, name: 'Bailarina (o)' },
  { code: 101, name: 'Bancário(a)' },
  { code: 102, name: 'Biólogo(a)' },
  { code: 103, name: 'Biomédico (a)' },
  { code: 104, name: 'Cabeleireiro(a)' },
  { code: 105, name: 'Caminhoneiro (a)' },
  { code: 106, name: 'carregador' },
  { code: 107, name: 'Catador(a)' },
  { code: 108, name: 'Catraqueiro' },
  { code: 109, name: 'Chefe da Secretaria de Expediente' },
  { code: 110, name: 'Chefe de Recursos Humanos' },
  { code: 111, name: 'Chefe de Serviços de Transporte' },
  { code: 112, name: 'Cirurgião(ã) Dentista' },
  { code: 113, name: 'Citricultor(a)' },
  { code: 114, name: 'Coletor(a) de Material Reciclável' },
  { code: 115, name: 'Comerciante' },
  { code: 116, name: 'Comerciário(a)' },
  { code: 117, name: 'Comprador(a)' },
  { code: 118, name: 'Comunicador(a) Social' },
  { code: 119, name: 'Condutor(a) Autônomo(a)' },
  { code: 120, name: 'Condutor(a) Escolar' },
  { code: 121, name: 'Conferente' },
  { code: 122, name: 'construtor' },
  { code: 123, name: 'Consultor(a) Administrativo' },
  { code: 124, name: 'Consultor(a) de Vendas' },
  { code: 125, name: 'Contabilista' },
  { code: 126, name: 'Contador(a)' },
  { code: 127, name: 'Contramestre' },
  { code: 128, name: 'Controller' },
  { code: 129, name: 'Coordenador(a)' },
  { code: 130, name: 'Coordenador(a) Administrativo Pessoal' },
  { code: 131, name: 'Coordenador(a) de Atendimento' },
  { code: 132, name: 'Coordenador(a) de Controladoria' },
  { code: 133, name: 'Coordenador(a) de Controle de Qualidade' },
  { code: 134, name: 'Coordenador(a) de Controle Interno' },
  { code: 135, name: 'Coordenador(a) de Engenharia Industrial' },
  { code: 136, name: 'Coordenador(a) de Exportação' },
  { code: 137, name: 'Coordenador(a) de Impostos' },
  { code: 138, name: 'Coordenador(a) de Instrumentos' },
  { code: 139, name: 'Coordenador(a) de Manutenção' },
  { code: 140, name: 'Coordenador(a) de Produção' },
  { code: 141, name: 'Coordenador(a) de Projetos' },
  { code: 142, name: 'Coordenador(a) de Recursos Humanos' },
  { code: 143, name: 'Coordenador(a) de Suprimentos' },
  { code: 144, name: 'Coordenador(a) de Transportes' },
  { code: 145, name: 'Coordenador(a) de Vendas' },
  { code: 146, name: 'Coordenador(a) Pedagógico(a)' },
  { code: 147, name: 'Coreógrafo' },
  { code: 148, name: 'Corretor(a) de Imóveis' },
  { code: 149, name: 'Corretor(a) de Seguros' },
  { code: 150, name: 'Costureiro(a)' },
  { code: 151, name: 'Cozinheiro(a)' },
  { code: 152, name: 'Cronoanalista' },
  { code: 153, name: 'Cuidador(a) de idoso' },
  { code: 154, name: 'Dançarina' },
  { code: 155, name: 'Delegado' },
  { code: 156, name: 'Dentista' },
  { code: 157, name: 'Desenvolvedor de Arte' },
  { code: 158, name: 'Desenvolvedor de Produtos Texteis' },
  { code: 159, name: 'Despachante' },
  { code: 160, name: 'Digitador(a)' },
  { code: 161, name: 'Diretor' },
  { code: 162, name: 'Diretor (a) Executivo (a)' },
  { code: 163, name: 'Diretor de Escola' },
  { code: 164, name: 'Diretor de Recursos Humanos' },
  { code: 165, name: 'Diretor(a) de Assuntos Técnicos' },
  { code: 166, name: 'Diretor(a) de Criação' },
  { code: 167, name: 'Diretor(a) de Produções' },
  { code: 168, name: 'Diretor(a) de Relações Públicas' },
  { code: 169, name: 'Diretor(a) de Relações Públicas e Sociais' },
  { code: 170, name: 'Do lar' },
  { code: 171, name: 'Economista' },
  { code: 172, name: 'Eletricista' },
  { code: 173, name: 'Eletricitário' },
  { code: 174, name: 'Embalador(a)' },
  { code: 175, name: 'Embalador(a) de Produtos' },
  { code: 176, name: 'Empregada Doméstica' },
  { code: 177, name: 'Empresário(a)' },
  { code: 178, name: 'Empresário(a) Rural' },
  { code: 179, name: 'Encarregado Automotivo' },
  { code: 180, name: 'Encarregado de Controladoria' },
  { code: 181, name: 'Encarregado(a)' },
  { code: 182, name: 'Encarregado(a) de Mídia' },
  { code: 183, name: 'Enfermeiro(a)' },
  { code: 184, name: 'Engenheiro(a)' },
  { code: 185, name: 'Engenheiro(a) Administrador(a)' },
  { code: 186, name: 'Engenheiro(a) Agrônomo(a)' },
  { code: 187, name: 'Engenheiro(a) Civil' },
  { code: 188, name: 'Engenheiro(a) de Alimentos' },
  { code: 189, name: 'Engenheiro(a) de Desenvolvimento Ambiental' },
  { code: 190, name: 'Engenheiro(a) de Segurança do Trabalho' },
  { code: 191, name: 'Engenheiro(a) Eletricista' },
  { code: 192, name: 'Engenheiro(a) Florestal' },
  { code: 193, name: 'Engenheiro(a) Mecânico' },
  { code: 194, name: 'Engenheiro(a) Naval' },
  { code: 195, name: 'Engenheiro(a) Químico(a)' },
  { code: 196, name: 'Escrevente Técnico Judiciário' },
  { code: 197, name: 'Escrituraria' },
  { code: 198, name: 'Escriturario(a)' },
  { code: 199, name: 'Especialista em Banco de Dados' },
  { code: 200, name: 'Estudante' },
  { code: 201, name: 'Farmacêutica(o)' },
  { code: 202, name: 'Faturista' },
  { code: 203, name: 'faxineira (o)' },
  { code: 204, name: 'Ferramenteiro' },
  { code: 205, name: 'Ferroviário' },
  { code: 206, name: 'Fisioterapeuta' },
  { code: 207, name: 'Floricultor(a)' },
  { code: 208, name: 'Fotógrafo(a)' },
  { code: 209, name: 'Funcionário(a) Público(a)' },
  { code: 210, name: 'funileiro' },
  { code: 211, name: 'Geógrafo(a)' },
  { code: 212, name: 'Geólogo(a)' },
  { code: 213, name: 'Gerente' },
  { code: 214, name: 'Gerente de Área' },
  { code: 215, name: 'Gerente de Contabilidade' },
  { code: 216, name: 'Gerente de Crédito e Cobrança' },
  { code: 217, name: 'Gerente de Faturamento' },
  { code: 218, name: 'Gerente de Recursos Humanos' },
  { code: 219, name: 'Gerente de Serviços de Transporte' },
  { code: 220, name: 'Gerente de Sistemas' },
  { code: 221, name: 'Gerente de Tecnologa da Informação' },
  { code: 222, name: 'Gerente de Tributário' },
  { code: 223, name: 'Gerente de Vendas' },
  { code: 224, name: 'Gerente de Vendas Distribuidores' },
  { code: 225, name: 'Gerente Departamento de Compra' },
  { code: 226, name: 'Gerente Financeiro' },
  { code: 227, name: 'Gerente Operacional' },
  { code: 228, name: 'Gerente Regional de Vendas' },
  { code: 229, name: 'Gestor(a) de Logística' },
  { code: 230, name: 'Gestor(a) de Negócios' },
  { code: 231, name: 'Gestor(a) de Projetos' },
  { code: 232, name: 'Gestor(a) Financeiro' },
  { code: 233, name: 'Impressor' },
  { code: 234, name: 'Industriário(a)' },
  { code: 235, name: 'Inspetor de Qualidade' },
  { code: 236, name: 'Instrumentista' },
  { code: 237, name: 'Intérprete' },
  { code: 238, name: 'Jardineiro' },
  { code: 239, name: 'Jornalista' },
  { code: 240, name: 'Lavrador(a)' },
  { code: 241, name: 'Líder de Embalagem' },
  { code: 242, name: 'Líder de Higienização' },
  { code: 243, name: 'Líder de Recepção' },
  { code: 244, name: 'Marceneiro' },
  { code: 245, name: 'Matemático(a)' },
  { code: 246, name: 'Mecânico' },
  { code: 247, name: 'Mecânico de Manutenção' },
  { code: 248, name: 'Medico(a)' },
  { code: 249, name: 'Médico(a) Pediátrico(a)' },
  { code: 250, name: 'Médico(a) Veterinário(a)' },
  { code: 251, name: 'Metalúrgico' },
  { code: 252, name: 'Militar' },
  { code: 253, name: 'Ministro Religioso' },
  { code: 254, name: 'Motorista' },
  { code: 255, name: 'Nutricionista' },
  { code: 256, name: 'Odontólogo (a)' },
  { code: 257, name: 'Oficial de Cartório' },
  { code: 258, name: 'Oficial de Justiça' },
  { code: 259, name: 'Oficial de Promotoria' },
  { code: 260, name: 'Oleiro(a)' },
  { code: 261, name: 'Operador (a)' },
  { code: 262, name: 'Operador (a) de Crédito Rural' },
  { code: 263, name: 'Operador de Caldeira' },
  { code: 264, name: 'Operador de Conicaleira' },
  { code: 265, name: 'Operador de Máquina' },
  { code: 266, name: 'Operador de Texturização' },
  { code: 267, name: 'Operador(a) de Caldeira' },
  { code: 268, name: 'Operador(a) de Forming' },
  { code: 269, name: 'Operador(a) de Imagem' },
  { code: 270, name: 'Operador(a) de Máquinas' },
  { code: 271, name: 'Orientador(a) Educacional' },
  { code: 272, name: 'Pecuarista' },
  { code: 273, name: 'Pedagogo(a)' },
  { code: 274, name: 'pedreiro' },
  { code: 275, name: 'Pedreiro Refratarista' },
  { code: 276, name: 'Planejador(a) de Manutenção' },
  { code: 277, name: 'Policial' },
  { code: 278, name: 'Policial Rodoviário' },
  { code: 279, name: 'Porteiro(a)' },
  { code: 280, name: 'Prensista' },
  { code: 281, name: 'Produtor (a)' },
  { code: 282, name: 'Produtor(a) Agropecuário' },
  { code: 283, name: 'Produtor(a) Rural' },
  { code: 284, name: 'Professor(a)' },
  { code: 285, name: 'Profissional Liberal' },
  { code: 286, name: 'Programador(a)' },
  { code: 287, name: 'Psicólogo(a)' },
  { code: 288, name: 'Publicitário(a)' },
  { code: 289, name: 'Químico(a)' },
  { code: 290, name: 'Reciclador(a)' },
  { code: 291, name: 'Reciclador(a) Ambiental Autônomo(a)' },
  { code: 292, name: 'Recobridor' },
  { code: 293, name: 'Representante Comercial' },
  { code: 294, name: 'Secretária Bilíngue' },
  { code: 295, name: 'Secretária de Diretoria' },
  { code: 296, name: 'Secretária Executiva' },
  { code: 297, name: 'Secretária(o)' },
  { code: 298, name: 'Securitário(a)' },
  { code: 299, name: 'Segurança' },
  { code: 300, name: 'Selecionador(a)' },
  { code: 301, name: 'Serralherio' },
  { code: 302, name: 'Servidor(a) Público(a)' },
  { code: 303, name: 'Sociólogo' },
  { code: 304, name: 'Supervisor(a)' },
  { code: 305, name: 'Supervisor(a) Administrativo' },
  { code: 306, name: 'Supervisor(a) de Adminstração de Pessoal' },
  { code: 307, name: 'Supervisor(a) de Atendimento' },
  { code: 308, name: 'Supervisor(a) de Compras' },
  { code: 309, name: 'Supervisor(a) de Custos' },
  { code: 310, name: 'Supervisor(a) de Elétrica e Instrumentação' },
  { code: 311, name: 'Supervisor(a) de Manufatura' },
  { code: 312, name: 'Supervisor(a) de Manutenção Industrial' },
  { code: 313, name: 'Supervisor(a) de Matéria-Prima' },
  { code: 314, name: 'Supervisor(a) de Operações' },
  { code: 315, name: 'Supervisor(a) de Produção' },
  { code: 316, name: 'Supervisor(a) de Recursos Humanos' },
  { code: 317, name: 'Supervisor(a) de Suprimentos' },
  { code: 318, name: 'Supervisor(a) de Tesouraria' },
  { code: 319, name: 'Supervisor(a) Financeiro' },
  { code: 320, name: 'Supervisor(a) Fiscal' },
  { code: 321, name: 'Tabelião' },
  { code: 322, name: 'Taxista' },
  { code: 323, name: 'Tecelão' },
  { code: 324, name: 'Técinico em Kaizen' },
  { code: 325, name: 'Técnica Agropecuária' },
  { code: 326, name: 'Técnico (a) Administrativo (a)' },
  { code: 327, name: 'Técnico de Métodos Gráficos' },
  { code: 328, name: 'Técnico de Operação de Usina Hidrelétrica' },
  { code: 329, name: 'Técnico de Tinturaria' },
  { code: 330, name: 'Técnico em Informática' },
  { code: 331, name: 'Técnico em Processamento' },
  { code: 332, name: 'Técnico(a) Agrícola' },
  { code: 333, name: 'Técnico(a) de Enfermagem' },
  { code: 334, name: 'Técnico(a) de Gesso' },
  { code: 335, name: 'Técnico(a) de Manutenção Elétrico' },
  { code: 336, name: 'Técnico(a) de Processos' },
  { code: 337, name: 'Técnico(a) em Contabilidade' },
  { code: 338, name: 'Técnico(a) em Edificações' },
  { code: 339, name: 'Técnico(a) em Eletrônica' },
  { code: 340, name: 'Técnico(a) em Informática' },
  { code: 341, name: 'Técnico(a) em Meio Ambiente' },
  { code: 342, name: 'Técnico(a) em Plástico' },
  { code: 343, name: 'Técnico(a) em Radiologia Médica' },
  { code: 344, name: 'Técnico(a) em Segurança do Trabalho' },
  { code: 345, name: 'Técnico(a) Mecânico(a)' },
  { code: 346, name: 'Técnico(a) Químico Industrial' },
  { code: 347, name: 'Tecnólogo do Produto Sênior' },
  { code: 348, name: 'Tecnólogo em Gestão Financeira' },
  { code: 349, name: 'Tecnólogo em Telecomunicações' },
  { code: 350, name: 'Tecnólogo(a)' },
  { code: 351, name: 'Tecnólogo(a) de Processo de Produção' },
  { code: 352, name: 'Tecnólogo(a) em Processamento de Dados' },
  { code: 353, name: 'Tecnólogo(a) Mecânico' },
  { code: 354, name: 'Telefonista' },
  { code: 355, name: 'Tintureiro' },
  { code: 356, name: 'Torneiro Mecânico' },
  { code: 357, name: 'Tradutor(a)' },
  { code: 358, name: 'Urdidor' },
  { code: 359, name: 'Vendedor(a)' },
  { code: 360, name: 'Vidreiro(a)' },
  { code: 361, name: 'Vigilante' },
  { code: 362, name: 'Web Designer' },
  { code: 363, name: 'Zootécnico(a)' }
]
